### ISSUE TITLE
Warning: A component is `contentEditable` and contains `children` managed by React

### ISSUE THREAD

**Issue by jakub-zawislak** [alibaba/GGEditor#400]
## 版本

GGEditor 3.0.0-beta.3

## 环境

React 16.11.0

## 重现链接

I have created a simple app using the create-react-app: [demo source](https://github.com/jakub-zawislak/ggeditor-3.0-demo)

I tried the same on the codesandbox, but I have compilation errors there. [demo on codesandbox](https://codesandbox.io/s/ggeditor-flow-8uytt)

## 重现步骤

Just use any 3.0.0 version of gg-editor. 

## 期望的结果是什么

Working app.

## 实际的结果是什么

> Warning: A component is `contentEditable` and contains `children` managed by React. It is now your responsibility to guarantee that none of those nodes are unexpectedly modified or duplicated. This is probably not intentional.

It works on the 2.0.4 version of GGEditor. Also, the 2.0.4 doesn't have any `contentEditable` attributes. in the source code. Maybe this will help: [suppressContentEditableWarning](https://github.com/facebook/draft-js/issues/81#issuecomment-252424597)
